# -*- coding: utf-8 -*-
"""A* Algorithm_Reproduced.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11x_NnS4StLz6DV-GduNHBTjZpo5qZt-V
"""

import heapq

graph = {
    "Lahore": {"Islamabad": 100, "Faisalabad": 760},
    "Islamabad": {"Lahore": 210, "Peshawar": 870},
    "Faisalabad": {"Lahore": 320, "Multan": 980},
    "Multan": {"Faisalabad": 430, "Karachi": 1000},
    "Peshawar": {"Islamabad": 540},
    "Karachi": {"Multan": 650}
}

heuristic = {
    "Lahore": 2210,
    "Islamabad": 3100,
    "Faisalabad": 500,
    "Multan": 770,
    "Peshawar": 1300,
    "Karachi": 0
}

def a_steric_alogorithm(graph, start, goal, heuristic):
    open_list = []
    heapq.heappush(open_list, (heuristic[start], [start]))
    g_costs = {start: 0}
    closed_set = set()

    while open_list:
        f, path = heapq.heappop(open_list)
        node = path[-1]

        if node == goal:
            return path, g_costs[node]

        if node in closed_set:
            continue

        closed_set.add(node)

        for neighbor, cost in graph[node].items():
            tentative_g = g_costs[node] + cost
            if neighbor not in g_costs or tentative_g < g_costs[neighbor]:
                g_costs[neighbor] = tentative_g
                f_cost = tentative_g + heuristic.get(neighbor, float('inf'))
                new_path = path + [neighbor]
                heapq.heappush(open_list, (f_cost, new_path))

    return None, float('inf')

if __name__ == "__main__":
    start_city = "Lahore"
    goal_city = "Karachi"
    path, cost = a_steric_alogorithm(graph, start_city, goal_city, heuristic)
    print("A* path:", path)
    print("Total cost:", cost)