# -*- coding: utf-8 -*-
"""AI1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YI2m16F9HRI6f5ar0rdkzyfDOx-wx1cG
"""

print("ASIM")
a=9
b=5
sum=a+b
sub=a-b
pro=a*b
div=a/b
print("Sum = "+sum)
print("Subtraction = "+sub)
print("Product = "+pro)
print("division = "+div)

"""

*  **MY NAME:**
*  **ADDITION:**
*  **SUBTRACTION:**
*  **MULTIPLICATION:**
*   **DIVISION:**






"""