# -*- coding: utf-8 -*-
"""AI list,tuples..9/11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zmPTT_tNCn-v_fvbq4HyUIkcoEucSLQo
"""



"""**MatplotLib:**

Matplotlib is a Python library used to create static, interactive, and animated visualizations like graphs and charts. It helps you plot data easily and clearly.

**Numpy:**

NumPy is a Python library that helps you work with large collections of numbers and perform math operations on them quickly and easily. It provides powerful tools for handling arrays and matrices, which are like lists but more efficient for calculations.
*NumPy* makes math with big sets of numbers faster and simpler.

**List:**

A List is an ordered collection of items where you can store multiple values in a single variable. You can add, remove, or access items by their position (called an index). Lists can hold different types of data, like numbers, text, or even other lists.
"""

my_list=[1,2,3,4,5,6,7,8,9,10]
print(my_list)
print('Sum: ',sum(my_list))
print('Max: ',max(my_list))
print('Min: ',min(my_list))

my_list.append(11)
my_list.remove(4)
print('Updated List ' ,my_list)


print('Sorted List: ',sorted(my_list))
print('Reversed List: ',my_list[::-1])

"""**Tuple:**

A Tuple is an ordered collection of items, similar to a list, but it cannot be changed after it’s created (it’s immutable). You can store multiple values in a tuple, and access them by their position (index), but you can’t add, remove, or modify the items later.

In short, a tuple is like a fixed list.
"""

fruits = ("Apple", "Mango", "Orange", "Grapes")
print('First Fruit: ', fruits[0])
print(fruits)

print('Updated Fruits:')
fruit_list =list(fruits)
fruit_list[1] = 'Banana'
print(fruit_list)

"""**Set:**

A Set is an unordered collection of unique items. Unlike lists or tuples, sets don’t keep items in any particular order, and they automatically remove duplicates. You can use sets to do things like check if something is in the collection, or find common items between groups.

In short, a set is like a bag of unique stuff with no order.
"""

set_1 = {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20}
set_2 = {2,4,6,8,10,12,14,16,18,20}

print('Set 1:')
print(set_1)
print('')

print('Set 2:')
print(set_2)
print('')

print('Union:')
print(set_1.union(set_2))
print('')

print('Intersection:')
print(set_1.intersection(set_2))
print('')

print('Difference:')
print(set_1.difference(set_2))


set_1.add(22)
print('')
print('Updated Set 1:')
print(set_1)

set_2.add(12)
print('')
print('Updated Set 2:')
print(set_2)

"""**Dictionary:**"""

student ={'Asim':85, 'Ali':11, 'Ahmed': 22}
print(student)

student2 ={'Asim':85, 'Asim':11, 'Asim': 22}

print(student2)