# -*- coding: utf-8 -*-
"""Lab1AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ANbTSjbeyp-XZGSkySdDvS-qBk_ILd_a

**Python Basics:**
"""

print("Asim")
print ("I'm an AI Student")

"""**Comments:**"""

#This is for practice
print("You can Comment in Python")

"""**Variables:**"""

fname ="Asim "
lstname= "Saleem"
fullname= fname+ lstname
print(fname)
print(lstname)
print(fullname)

"""**Type Casting:**"""

a= str ("asim")
b= int (4)
c= float(4)
print(a)
print(b)
print(c)

"""**Type Of Variable:**"""

x=11.5
y="AI"
z= 1
print(type(x))
print(type(y))
print(type(z))

"""**Case Sensitive:**"""

a=10
A="ASIM"
print(a)
print(A)

"""**Variable Names:**"""

_var =1
Var =2
VAR=3
_var_ =4

print(_var)
print(Var)
print(VAR)
print(_var_)

"""**Multi Values To Multi Variables:**"""

a,b,c = 1,2,"c"
print(a)
print(b)
print(c)

"""**Multi Variables Single Value:**"""

a=b=c = "Apple"

"""**Global Variable:**"""

x ="Global Variable"

def func():

 print("X is a "+ x)

func()

"""***Dictionary:***
Dictionaries are use to store data using pair of a unique key and value.
"""

dict = {
  "city": "Abbottabad",
  "Year": "2025",
  1: "Asim"
}
print(dict[1])
print(dict["city"])

"""**Duplicate Values:**
Duplicate Values are not allowed in dictionaries.
"""

dict = {1:"A",
        2:"B",
        2: "C"
}

print(dict)

