# -*- coding: utf-8 -*-
"""waterjug problem answers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sqFbCmbxS14ENdeh5Xpegvhr20ivZwJJ

**Reflection Questions:**

 **Compare the solution paths found by BFS, DFS, and A*.**

BFS → finds the shortest path (e.g., 4 steps above).

DFS → may find a longer path or even loop without reaching the goal unless controlled.

A* → finds the same shortest path as BFS, but usually with fewer state expansions (faster if heuristic is good).



 **Which algorithm gives the shortest path? Why?**
 BFS and A* give the shortest path.

DFS does not guarantee shortest.

BFS guarantees shortest because it expands states level by level.

A* guarantees shortest because its heuristic is admissible (doesn’t overestimate).






**Which algorithm is more efficient in terms of time and memory?**
DFS → Most memory efficient (stores only one path at a time), but not reliable.

BFS → Time-consuming and memory-heavy because it stores all frontier nodes.

A* → More efficient than BFS (fewer expansions), but needs heuristic calculation and priority queue.
"""